Repository HikeMate/hikeMateApp, pull requests merged in 2024-12, with the labels that each got.

#227 fix: planned hikes also appear in the saved hikes screen
  app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
Labels: sprint 8

#240 Fix/too big osm hike queries
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/overpassAPI/OverpassRepository.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Labels: enhancement, sprint 8

#232 feat(hikes): new HikesViewModel flows
  app/src/main/java/ch/hikemate/app/model/route/DeferredData.kt
  app/src/main/java/ch/hikemate/app/model/route/Hike.kt
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/test/java/ch/hikemate/app/model/route/DeferredDataTest.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeTest.kt
  app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
Labels: sprint 8

#237 feat: add details to run hike screen
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/components/BigButton.kt
  app/src/main/java/ch/hikemate/app/ui/components/DetailRow.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, sprint 8

#241 refactor: use new HikesViewModel
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/ZoomMapButtonTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/ui/components/CenteredLoadingAnimation.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
  app/src/main/java/ch/hikemate/app/ui/theme/Color.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
  app/src/main/res/values/strings.xml
Labels: sprint 8

#229 feat: add Location button to the elevation graph
  app/src/androidTest/java/ch/hikemate/app/ui/components/ElevationGraphTest.kt
  app/src/main/java/ch/hikemate/app/ui/components/ElevationGraph.kt
Labels: sprint 8

#244 fix: re-authenticate the user in-app instead of browser
  app/src/androidTest/java/ch/hikemate/app/ui/profile/DeleteAccountScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/authentication/AuthRepository.kt
  app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
  app/src/main/java/ch/hikemate/app/model/authentication/FirebaseAuthRepository.kt
  app/src/main/java/ch/hikemate/app/ui/profile/DeleteAccountScreen.kt
  app/src/test/java/ch/hikemate/app/authentication/AuthViewModelTest.kt
  app/src/test/java/ch/hikemate/app/authentication/FirebaseAuthRepositoryTest.kt
Labels: bug, sprint 8

#251 refactor(run): use `HikesViewModel`
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/res/values/strings.xml
Labels: sprint 8

#254 fix: back handler in hike details not in the right place
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
Labels: Sprint 9

#261 chore: handle nullable name in saved hike repo
  app/src/main/java/ch/hikemate/app/model/route/Hike.kt
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/main/java/ch/hikemate/app/model/route/saved/SavedHike.kt
  app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeTest.kt
Labels: enhancement, Sprint 9

#247 Fix/elevation graphs and difference altitude not working
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/ZoomMapButtonTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/elevation/ElevationRepository.kt
  app/src/main/java/ch/hikemate/app/model/elevation/ElevationRepositoryCopernicus.kt
  app/src/main/java/ch/hikemate/app/model/elevation/ElevationServiceRepository.kt
  app/src/main/java/ch/hikemate/app/model/route/DetailedHikeRoute.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/components/ElevationGraph.kt
  app/src/main/java/ch/hikemate/app/utils/RouteUtils.kt
  app/src/test/java/ch/hikemate/app/model/elevation/ElevationIntegrationTest.kt
  app/src/test/java/ch/hikemate/app/model/elevation/ElevationRepositoryCopernicusTest.kt
  app/src/test/java/ch/hikemate/app/model/elevation/ElevationRepositoryTest.kt
  app/src/test/java/ch/hikemate/app/model/elevation/ElevationServiceRepositoryTest.kt
  app/src/test/java/ch/hikemate/app/model/route/DetailedHikeRouteTest.kt
  app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
  app/src/test/java/ch/hikemate/app/model/route/LatLongTest.kt
  app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
  app/src/test/java/ch/hikemate/app/model/route/saved/SavedHikesViewModelTest.kt
  app/src/test/java/ch/hikemate/app/utils/RouteUtilsTest.kt
Labels: bug, sprint 8

#259 fix: ui jump when going from saved to planned
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
Labels: bug, Sprint 9

#270 fix: adapt Hike.kt and DetailedHike to the projection function
  app/src/androidTest/java/ch/hikemate/app/benchmark/LocationProjectionBenchmark.kt
  app/src/main/java/ch/hikemate/app/model/route/Hike.kt
  app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeTest.kt
  app/src/test/java/ch/hikemate/app/utils/LocationUtilsTest.kt
Labels: Sprint 9

#267 feat(hikes): error handling `HikesViewModel`
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/route/DeferredData.kt
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
Labels: Sprint 9

#257 fix: solve loop issue in the screens by signing out and navigating to Auth screen
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/ProfileScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/EditProfileScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/ProfileScreen.kt
Labels: Sprint 9

#235 feat: add mapstate that saves state of the map screen map
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
Labels: bug, sprint 8

#274 fix: bottom-bar nav overlapping with hikes
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Labels: bug, Sprint 9

#273 feat: project user location on hike in run hike
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/components/LocationPermissionAlertDialog.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
  app/src/test/java/ch/hikemate/app/utils/MapUtilsTest.kt
Labels: enhancement, Sprint 9

#272 test: End2End 3 about tutorial and profile
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest3.kt
  app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
Labels: enhancement, Sprint 9

#262 Fix/bug map too small
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
Labels: bug, Sprint 9

#276 feat: make hikes unplannable
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
Labels: enhancement, Sprint 9

#278 feat: increase location updates freq
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Labels: Sprint 9

#279 Chore: refactor to reduce code complexity
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Labels: Sprint 9

#248 feat: add facilities to the RunHike and HikeDetails screens
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesViewModel.kt
  app/src/main/java/ch/hikemate/app/model/facilities/Facility.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
  app/src/main/res/drawable/bbq.xml
  app/src/main/res/drawable/bench.xml
  app/src/main/res/drawable/biergarten.xml
  app/src/main/res/drawable/drinking_water.xml
  app/src/main/res/drawable/parking.xml
  app/src/main/res/drawable/ranger_station.xml
  app/src/main/res/drawable/restaurant.xml
  app/src/main/res/drawable/supermarket.xml
  app/src/main/res/drawable/toilets.xml
  app/src/main/res/drawable/waste_basket.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/model/facilities/FacilitiesViewModelTest.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeTest.kt
  app/src/test/java/ch/hikemate/app/utils/MapUtilsTest.kt
Labels: sprint 8

#285 fix: unplan this hike color
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 10

#290 fix: offline update profile, add timeout to go back.
  app/src/main/java/ch/hikemate/app/ui/profile/EditProfileScreen.kt
Labels: bug, Sprint 10

#298 fix: fix back buttons double clicks
  app/src/androidTest/java/ch/hikemate/app/ui/profile/DeleteAccountScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/components/BackButton.kt
Labels: bug, Sprint 10

#296 feat: display actual progression and user elevation in run
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt
  app/src/main/java/ch/hikemate/app/utils/RouteUtils.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/utils/LocationUtilsTest.kt
Labels: enhancement, Sprint 10

#302 fix: add a back button on HikeDetails and RunHike loading screen
  app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
Labels: bug, enhancement, Sprint 10

#301 feat: display the starting of a hike
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
Labels: enhancement, Sprint 10

#304 fix(hikes): unsaving hike in details
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
Labels: bug

#286 Improvement: delete unused files and unused imports
  app/src/main/java/ch/hikemate/app/model/route/DetailedHikeRoute.kt
  app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
  app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
  app/src/test/java/ch/hikemate/app/model/route/DetailedHikeRouteTest.kt
  app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
  app/src/test/java/ch/hikemate/app/model/route/saved/SavedHikesViewModelTest.kt
Labels: enhancement, Sprint 9, Sprint 10

#314 fix: ui glitching when clicking on already selected bottom item
  app/src/androidTest/java/ch/hikemate/app/navigation/BottomBarNavigationTest.kt
  app/src/main/java/ch/hikemate/app/ui/navigation/BottomBarNavigation.kt
Labels: bug, Sprint 10

#282 chore: fix ui breaking on small and big screens
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug, Sprint 10

#312 fix: display planned hikes dates
  app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
Labels: bug

#293 fix(bug): performance and display of facilities on first composition and facilities being drawn under the Route
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
  app/src/test/java/ch/hikemate/app/utils/MapUtilsTest.kt
Labels: bug, Sprint 10

#310 feat:add puck in run hike screen
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/utils/RouteUtils.kt
Labels: enhancement, Sprint 10

#317 chore/better-ui-ux
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/ZoomMapButtonTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/ProfileScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/profile/Profile.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeDifficulty.kt
  app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInWithEmailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/components/BigButton.kt
  app/src/main/java/ch/hikemate/app/ui/components/CenteredLoadingAnimation.kt
  app/src/main/java/ch/hikemate/app/ui/components/DetailRow.kt
  app/src/main/java/ch/hikemate/app/ui/components/ElevationGraph.kt
  app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt
  app/src/main/java/ch/hikemate/app/ui/guide/GuideScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/DeleteAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/EditProfileScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/ProfileScreen.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
  app/src/main/java/ch/hikemate/app/ui/theme/Color.kt
  app/src/main/java/ch/hikemate/app/ui/theme/Theme.kt
  app/src/main/java/ch/hikemate/app/ui/theme/Type.kt
  app/src/main/res/values/guide.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestoreTest.kt
  app/src/test/java/ch/hikemate/app/model/profile/ProfileViewModelTest.kt
Labels: enhancement, Sprint 10

#326 fix: fix unplanning label in hike details
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
Labels: Sprint 10

#329 feat: display message when too far
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 10

#321 feat: add password requirements hint
  app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 10

#322 fix(bug): operations in the HikeDetailsScreen show a toast when there is no internet connection
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesViewModel.kt
  app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesRepositoryFirestore.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug, Sprint 10

#330 fix: appearance of the hike start marker
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
  app/src/main/res/drawable/location_on.xml
Labels: Sprint 10

#311 fix: change the text of the error to be more broad
  app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 10

#334 fix: remove unused-data in xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 10

#332 Test/e2e4
  .github/workflows/ci.yml
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest4.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/components/DetailRow.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
Labels: enhancement, Sprint 10

#335 docs: update README
  README.md
  images/architecture-diagram-m3.svg
  images/details-screen.png
  images/guide.png
  images/map-screen.png
  images/planned-screen.png
  images/run-screen.png
Labels: documentation, Sprint 10

#336 fix: profile soft loop bug
  app/src/main/java/ch/hikemate/app/model/profile/ProfileViewModel.kt
Labels: bug, Sprint 10
