Repository HikeMate/hikeMateApp, pull requests merged in 2024-11, with the labels that each got.

#96 fix(map): fix map going out of world
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Labels: bug

#93 Feat/merge firebase auth with signin composable
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
  app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/authentication/FirebaseAuthRepository.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
Labels: enhancement

#126 fix(auth): fix go to map directly when signed in
  app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
Labels: bug

#128 fix(test): fix nav and end2end tests
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
  app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
Labels: bug

#115 Feat/hike details UI
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/ui/components/BackButton.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
  app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
  app/src/main/res/drawable/bookmark_filled_blue.xml
  app/src/main/res/drawable/bookmark_no_fill.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/utils/MapUtilsTest.kt
Labels: enhancement

#141 feat(hikes): add selectRouteById
  app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepository.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
  app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpassTest.kt
  app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
Labels: enhancement

#151 feat(saved): better error handling
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
  app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/components/CenteredErrorAction.kt
  app/src/main/java/ch/hikemate/app/ui/components/CenteredLoadingAnimation.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#97 feat: create Profile when a Profile hasn't been created
  app/src/androidTest/java/ch/hikemate/app/ui/auth/CreateAccountScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInWithEmailScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/ProfileScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileRepository.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileRepositoryDummy.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestore.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/ProfileScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/authentication/AuthViewModelTest.kt
  app/src/test/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestoreTest.kt
  app/src/test/java/ch/hikemate/app/model/profile/ProfileViewModelTest.kt
Labels: enhancement

#149 feat: HikeDetailScreen calls viewmodel to update the savedHikeList
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/utils/DatetimeUtils.kt
  app/src/test/java/ch/hikemate/app/model/route/saved/SavedHikesViewModelTest.kt
Labels: enhancement, sprint 5

#164 test(end2end): implement second end2end
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
Labels: sprint 5

#167 refactor(details): hike difficulty as enum
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/route/DetailedHikeRoute.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeDifficulty.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/model/route/DetailedHikeRouteTest.kt
Labels: sprint 6

#169 feat(routes): deterministic color for hikes
  app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/theme/Color.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeRouteTest.kt
Labels: sprint 6

#172 Fix/rename altitude difference to elevation gain
  app/src/main/java/ch/hikemate/app/model/route/DetailedHikeRoute.kt
  app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt
  app/src/main/java/ch/hikemate/app/utils/RouteUtils.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/model/route/DetailedHikeRouteTest.kt
  app/src/test/java/ch/hikemate/app/utils/RouteUtilsTest.kt
Labels: sprint 6

#184 ci: add jacoco code coverage to the ci
  .github/workflows/ci.yml
Labels: enhancement, sprint 6

#183 fix:aesthetic fixes for hike details screen
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeDifficulty.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/res/drawable/bookmark_no_fill.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, sprint 6

#159 feat: improve error handling in profile view model
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
  app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/ProfileScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileRepository.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestore.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileViewModel.kt
  app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInWithEmailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/components/CenteredErrorAction.kt
  app/src/main/java/ch/hikemate/app/ui/profile/EditProfileScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/ProfileScreen.kt
  app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/model/profile/ProfileViewModelTest.kt
  app/src/test/java/ch/hikemate/app/model/route/saved/SavedHikesViewModelTest.kt
Labels: sprint 5, sprint 6

#189 feat(auth): deleting a user from the ui
  app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/DeleteAccountScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/profile/ProfileScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/authentication/AuthRepository.kt
  app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
  app/src/main/java/ch/hikemate/app/model/authentication/FirebaseAuthRepository.kt
  app/src/main/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestore.kt
  app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
  app/src/main/java/ch/hikemate/app/ui/profile/DeleteAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/ProfileScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/hikemate/app/authentication/AuthViewModelTest.kt
  app/src/test/java/ch/hikemate/app/authentication/FirebaseAuthRepositoryTest.kt
Labels: enhancement, sprint 6

#191 feat: implement a Guide which contains instructions on hiking and HikeMate
  app/src/androidTest/java/ch/hikemate/app/ui/guide/GuideScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/guide/Guide.kt
  app/src/main/java/ch/hikemate/app/ui/guide/GuideScreen.kt
  app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
  app/src/main/res/values/guide.xml
  app/src/test/java/ch/hikemate/app/model/guide/GuideTest.kt
Labels: enhancement, sprint 6

#196 Fix/asynchronous operations
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
  app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInWithEmailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/components/BackButton.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Labels: bug, sprint 6

#205 ci: add logcat output as artifact in CI
  .github/workflows/ci.yml
Labels: sprint 7

#193 feat(routes): display the appropriateness message
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
  app/src/androidTest/java/ch/hikemate/app/ui/map/ZoomMapButtonTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/ui/components/AsyncStateHandler.kt
  app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Labels: enhancement, sprint 6, sprint 7

#203 fix: date line issues for hikes crossing and searching
  app/src/main/java/ch/hikemate/app/model/extensions/BoundingBoxExtension.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
  app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeRouteTest.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpassTest.kt
  app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
Labels: sprint 7

#194 feat: implement model and view model for retrieving trashcans restrooms and parkings
  app/build.gradle.kts
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesRepository.kt
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpass.kt
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesViewModel.kt
  app/src/main/java/ch/hikemate/app/model/facilities/Facility.kt
  app/src/main/java/ch/hikemate/app/model/overpassAPI/OverpassRepository.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
  app/src/test/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpassTest.kt
  app/src/test/java/ch/hikemate/app/model/facilities/FacilitiesViewModelTest.kt
  app/src/test/java/ch/hikemate/app/model/facilities/FacilityTest.kt
  gradle/libs.versions.toml
Labels: enhancement, sprint 6, sprint 7

#211 fix: change date picker to compose one
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/theme/Theme.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, sprint 7

#192 feat(hikes): implement HikesViewModel
  app/src/main/java/ch/hikemate/app/model/route/DeferredData.kt
  app/src/main/java/ch/hikemate/app/model/route/Hike.kt
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
  app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
Labels: sprint 6, sprint 7

#220 docs(hikes): fix typo in HikesViewModel docs
  app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
Labels: sprint 7

#218 refactor: replace and remove toFormattedDate
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/utils/DatetimeUtils.kt
Labels: sprint 7

#200 Fix/Sign up button not shown
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
  app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
  app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
  app/src/main/java/ch/hikemate/app/model/authentication/FirebaseAuthRepository.kt
  app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/auth/SignInWithEmailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/DeleteAccountScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/EditProfileScreen.kt
  app/src/main/java/ch/hikemate/app/ui/profile/ProfileScreen.kt
Labels: bug, sprint 7

#212 feat:implement run hike screen skeleton
  app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
  app/src/main/java/ch/hikemate/app/MainActivity.kt
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpass.kt
  app/src/main/java/ch/hikemate/app/model/overpassAPI/OverpassRepository.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
  app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
Labels: enhancement, sprint 7

#221 refactor: use jsonReader in facilities repo
  app/build.gradle.kts
  app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpass.kt
  app/src/test/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpassTest.kt
  gradle/libs.versions.toml
Labels: bug, sprint 7

#201 feat: create a function that maps user location to location on hike
  .gitignore
  app/build.gradle.kts
  app/src/androidTest/java/ch/hikemate/app/benchmark/LocationProjectionBenchmark.kt
  app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
  app/src/main/java/ch/hikemate/app/model/route/RouteSegment.kt
  app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt
  app/src/main/java/ch/hikemate/app/utils/RouteUtils.kt
  app/src/test/java/ch/hikemate/app/model/route/HikeRouteTest.kt
  app/src/test/java/ch/hikemate/app/utils/LocationUtilsTest.kt
  gradle/libs.versions.toml
Labels: sprint 7

#223 feat: implement run this hike button
  app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
  app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, sprint 7
